# ComfyUI Docker Compose File v1.0.1 by John Aldred
# http://www.johnaldred.com
# http://github.com/kaouthia

services:
  comfyk:
    build:
      context: .
      dockerfile: Dockerfile

    image: comfyui:latest
    container_name: comfyui

    ports:
      - "8188:8188"

    volumes:
      - ./models:/app/ComfyUI/models:rw
      - ./output:/app/ComfyUI/output:rw
      - ./input:/app/ComfyUI/input:rw
      - ./settings:/app/ComfyUI/user/default:rw
      - ./flows:/app/ComfyUI/user/default/workflows:rw
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    stdin_open: true
    tty: true
    restart: unless-stopped
